[context."netlify-dev"]
  environment = { ALGOLIA_INDEX_NAME = "staging_colinwilson.uk" }

## This rule rewrites to an external Plausible instance
[[redirects]]
  from = "/s/js/script.js"
  to = "https://plausible.aigis.io/js/script.js"
  status = 200
  force = false

[[redirects]]
  from = "/s/api/event"
  to = "https://plausible.aigis.io/api/event"
  status = 200
  force = false
